language: csharp
solution: Calculator.sln
os:
    - linux
env:
    - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
    - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release
    - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
    - TARGET_CPU=x86 BUILD_CONFIGURATION=Release
sudo: required
mono: none
dotnet: 2.1
dist: trusty
before_script:
  - dotnet restore
script:
  - dotnet test ./CalcTests -c Release -f netcoreapp2.1
